services:   
  mongo_junplid_prod:
    image: mongo:6.0 
    restart: unless-stopped
    env_file: .env.prod
    volumes:
      - ./data-mongo:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 120s
      start_period: 40s
      timeout: 5s
      retries: 3 
    networks: [rede_junplid_prod]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  postgres_junplid_prod:
    image: postgres:16-alpine
    restart: unless-stopped 
    env_file: .env.prod
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$${POSTGRES_USER}"]
      interval: 120s
      start_period: 40s
      timeout: 5s
      retries: 3
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks: [rede_junplid_prod]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  junplid:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: junplid_prod
    image: junplid-core-prod
    pull_policy: always
    # restart: unless-stopped
    env_file:
      - ./.env.prod
    depends_on:
      postgres_junplid_prod:
        condition: service_healthy
      mongo_junplid_prod:
        condition: service_healthy
    ports:
      - 127.0.0.1:4000:4000
    volumes:
      - ./app/storage-prod:/app/storage-prod
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:4000/v1/public/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks: [rede_junplid_prod] 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  rede_junplid_prod:
    driver: bridge